# Generated by Django 3.2 on 2021-05-10 00:56

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stockInfopage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('memo', jsonfield.fields.JSONField(default={}, dump_kwargs={'ensure_ascii': False})),
            ],
        ),
    ]
