# Generated by Django 3.2 on 2021-05-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockInfopage', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='memo',
            field=models.TextField(),
        ),
    ]
