# Generated by Django 3.2.2 on 2021-05-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockInfopage', '0003_alter_book_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=40)),
                ('last_update', models.DateField()),
            ],
        ),
    ]
