# Generated by Django 3.2.2 on 2021-05-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockInfopage', '0004_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name=6),
        ),
    ]
