# Generated by Django 3.2.2 on 2021-05-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockInfopage', '0005_alter_company_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('code', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('open', models.BigIntegerField()),
                ('high', models.BigIntegerField()),
                ('low', models.BigIntegerField()),
                ('close', models.BigIntegerField()),
                ('diff', models.BigIntegerField()),
                ('volume', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
