# Generated by Django 4.2.1 on 2023-05-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockInfopage", "0006_auto_20210521_1725"),
    ]

    operations = [
        migrations.CreateModel(
            name="Detaildaily",
            fields=[
                ("code", models.CharField(max_length=128)),
                ("company", models.CharField(max_length=40)),
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("open", models.BigIntegerField()),
                ("high", models.BigIntegerField()),
                ("low", models.BigIntegerField()),
                ("close", models.BigIntegerField()),
                ("diff", models.BigIntegerField()),
                ("volume", models.BigIntegerField()),
            ],
        ),
    ]
